### ISSUE TITLE
Primary Not Agile

### ISSUE THREAD

**Issue by PurpleTux** [BogRtM/Pathfinder#24]
It always feels like I'm not able to keep up with enemies when using the primary, maybe making it agile will help. It also will help with dodging. Mercenary and Loader are the two melee characters in the base game, and Mercenary has an agile primary and Loader is meant to tank. I understand that Pathfinder is not a fully melee character, but they are too frail to not have access to better dodging abilities.

**Comment by Darkmega18** [comment]
secondary dash + throw and bola?
